# [START gae_flex_quickstart_yaml]
runtime: nodejs10
service: guess-who-admin
instance_class: F2
automatic_scaling:
  min_instances: 0
  max_instances: 1
  max_idle_instances: 1
  target_cpu_utilization: 0.9

env_variables:
  DATABASE_HOST: '35.233.83.31'
  DATABASE_PORT: 5432
  DATABASE_NAME: 'postgres'
  DATABASE_USERNAME: 'developer'
  DATABASE_PASSWORD: 'cxJu3RK5QXzNuf9Y'
  NODE_ENV: 'production'
  INSTANCE_CONNECTION_NAME: 'guess-who-232508:europe-west1:guess-who-database'

beta_settings:
  cloud_sql_instances: 'guess-who-232508:europe-west1:guess-who-database'
