version: 2
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Install jq
          command: |
            apt-get -y update && apt-get -y install jq
      - run:
          name: Auth google cloud
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run:
          name: Deploy app
          command: |
            if gcloud app versions list --service=${GCLOUD_SERVICE} --format="json"; then
              gcloud --quiet app deploy -v=$(gcloud app versions list --service=${GCLOUD_SERVICE} --format="json" | jq -r '.[0].version.id')
            else
              gcloud --quiet app deploy
            fi
